apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
status: {}
