apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  strategy: {}
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: examplevotingapp-result-jd2nn
        ports:
        - containerPort: 80
        resources: {}
status: {}
